# .streamlit/secrets.toml

[connections.tidb]
dialect = "mysql"
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
port = 4000
database = "expenses"
username = "J5Zrj7vHZikh2QV.root"
password = "kN8NmcZTmE9tnwoo"